version: '3.8'

services:
  app:
    build:
      context: .
      args:
        - NEXT_PUBLIC_API_URL=https://digital-twin.hanifaslam.dev/api
        - NEXT_PUBLIC_DISABLE_CSRF=true
    container_name: nextjs_app
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=https://digital-twin.hanifaslam.dev/api
    ports:
      - '3000:3000'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
